// ==========================================
// 1. SAMPLE SEED DATA (RELATIONAL WITH 152 MEMBERS)
// ==========================================

const SAMPLE_MEMBERS = [
  // Original Seed Leaders (IDs 1-8)
  { id: 1, name: 'Juan Dela Cruz', chapter_area: 'EAST', role: 'Chapter Servant', contact: '+63 912 345 6789', email: 'juan.east@example.com', status: 'Active', age: 32, birthday: '1994-04-12', address: 'Tarlac City', parents_contact: '' },
  { id: 2, name: 'Maria Santos', chapter_area: 'WEST', role: 'Household Head', contact: '+63 922 456 7890', email: 'maria.west@example.com', status: 'Active', age: 28, birthday: '1998-09-21', address: 'Sta. Ignacia, Tarlac', parents_contact: '' },
  { id: 3, name: 'Pedro Penduko', chapter_area: 'AREA', role: 'Unit Head', contact: '+63 933 567 8901', email: 'pedro.area@example.com', status: 'Active', age: 35, birthday: '1991-07-07', address: 'Moncada, Tarlac', parents_contact: '' },
  { id: 4, name: 'Ana Gomez', chapter_area: 'NORTH', role: 'Area Coordinator', contact: '+63 944 678 9012', email: 'ana.north@example.com', status: 'Active', age: 30, birthday: '1996-11-15', address: 'Moncada, Tarlac', parents_contact: '' },
  { id: 5, name: 'Jose Rizal', chapter_area: 'SOUTH', role: 'Core Member', contact: '+63 955 789 0123', email: 'jose.south@example.com', status: 'Inactive', age: 40, birthday: '1986-06-19', address: 'Concepcion, Tarlac', parents_contact: '' },
  { id: 6, name: 'Clara Del Pilar', chapter_area: 'UPPER CORE', role: 'Chapter Servant', contact: '+63 916 234 5678', email: 'clara.uc@example.com', status: 'Active', age: 29, birthday: '1997-03-05', address: 'Paniqui, Tarlac', parents_contact: '' },
  { id: 7, name: 'Andres Bonifacio', chapter_area: 'LIT', role: 'LIT Head', contact: '+63 927 345 6789', email: 'andres.lit@example.com', status: 'Active', age: 26, birthday: '2000-11-30', address: 'Tarlac City', parents_contact: '' },
  { id: 8, name: 'Gabriela Silang', chapter_area: 'TRAINING', role: 'Training Head', contact: '+63 938 456 7890', email: 'gabriela.training@example.com', status: 'Active', age: 27, birthday: '1999-05-10', address: 'Paniqui, Tarlac', parents_contact: '' },

  // 64 New Members imported from Spreadsheet (IDs 9-72)
  { id: 9, name: 'Mark Allen S. Nosaves', chapter_area: 'EAST', role: 'Member', contact: '9923937559', email: '', status: 'Active', age: 13, birthday: '3/23/2013', address: 'Matatalaib, Tarlac', parents_contact: '9919235478' },
  { id: 10, name: 'Precious Diane Z. Samson', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 13, birthday: '3/20/2013', address: 'San Manuel, Tarlac', parents_contact: '9919235478' },
  { id: 11, name: 'Clark Kent Z. Samson', chapter_area: 'EAST', role: 'Member', contact: '9933643376', email: '', status: 'Active', age: 10, birthday: '8/24/2016', address: 'San Manuel, Tarlac', parents_contact: '9919235478' },
  { id: 12, name: 'Cedrick Jewel G. Puyawan', chapter_area: 'EAST', role: 'Member', contact: '9455002513', email: '', status: 'Active', age: 14, birthday: '9/12/2011', address: 'San Manuel, Tarlac', parents_contact: '99546284287' },
  { id: 13, name: 'Jhozhua L. Corpuz', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 13, birthday: '12/29/2012', address: 'San Manuel, Tarlac', parents_contact: '9108330947' },
  { id: 14, name: 'Enzo Luis A. Labon', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '10/28/2011', address: 'San Manuel, Tarlac', parents_contact: '' },
  { id: 15, name: 'Jhaztin Carl Corpuz', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 16, birthday: '02/28/2010', address: 'San Manuel, Tarlac', parents_contact: '9108330973' },
  { id: 16, name: 'John Marion Sigua', chapter_area: 'EAST', role: 'Member', contact: '9122712254', email: '', status: 'Active', age: 12, birthday: '09/08/2013', address: 'Maliwalo Tarlac', parents_contact: '9456885921' },
  { id: 17, name: 'Carmelo Anthony G. Sigua', chapter_area: 'EAST', role: 'Member', contact: '9153025737', email: '', status: 'Active', age: 16, birthday: '09/28/2009', address: 'Maliwalo Tarlac', parents_contact: '9456885921' },
  { id: 18, name: 'Jovel D. Garcia', chapter_area: 'EAST', role: 'Member', contact: '9038360124', email: '', status: 'Active', age: 14, birthday: '7/19/2011', address: 'Maliwalo Tarlac', parents_contact: '9386956160' },
  { id: 19, name: 'Jeanette Mary Salazar', chapter_area: 'EAST', role: 'Member', contact: '9101388805', email: '', status: 'Active', age: 18, birthday: '9/8/2007', address: 'Sitio Buni Bura', parents_contact: '9094708294' },
  { id: 20, name: 'Jeonard Francis Catap', chapter_area: 'EAST', role: 'Member', contact: '9701807117', email: '', status: 'Active', age: 18, birthday: '8/29/2007', address: 'Culipat, Tarlac City', parents_contact: '9121256554' },
  { id: 21, name: 'Miguel Antonio TaÃ±edo', chapter_area: 'EAST', role: 'Member', contact: '9919791125', email: '', status: 'Active', age: 18, birthday: '10/18/2011', address: 'San Sebastian, Tarlac City', parents_contact: '9584887998' },
  { id: 22, name: 'Gabriel R. Magat', chapter_area: 'EAST', role: 'Member', contact: '9604136208', email: '', status: 'Active', age: 14, birthday: '01/16/2012', address: 'Sitio Calevo Tibag, Tarlac City', parents_contact: '9634409663' },
  { id: 23, name: 'Rajh Bernardo', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '11/21/2014', address: 'San Manuel, Tarlac', parents_contact: '94821456916' },
  { id: 24, name: 'Jaycee Antonio', chapter_area: 'EAST', role: 'Member', contact: '9202031881', email: '', status: 'Active', age: 14, birthday: '11/23/2011', address: 'Batang Batang Tarlac City', parents_contact: '9389293791' },
  { id: 25, name: 'Aljune Lagmay', chapter_area: 'EAST', role: 'Member', contact: '9564393473', email: '', status: 'Active', age: 16, birthday: '11/07/2012', address: 'Batang Batang Tarlac City', parents_contact: '' },
  { id: 26, name: 'Jilian Baquerto', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '05/05/2010', address: 'Lalapac Victoria Tarlac', parents_contact: '965817117' },
  { id: 27, name: 'Rocel Yusi', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 15, birthday: '7/31/2011', address: 'Lalapac Victoria Tarlac', parents_contact: '965817117' },
  { id: 28, name: 'Justine A. Officiar', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 15, birthday: '12/5/2010', address: 'Batang Batang Tarlac City', parents_contact: '9092069893' },
  { id: 29, name: 'Darlina Kathe Seaismundo', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 16, birthday: '05/05/2011', address: 'Batang Batang Tarlac City', parents_contact: '9670072185' },
  { id: 30, name: 'Karl Andrei Nunag', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '4/11/2011', address: 'Batang Batang Tarlac City', parents_contact: '951429950' },
  { id: 31, name: 'Johnny P. Eugenio', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '1/16/2012', address: 'Batang Batang Tarlac City', parents_contact: '9928788142' },
  { id: 32, name: 'Reeza Manthas L. Peralta', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 16, birthday: '3/8/2010', address: 'Batang Batang Tarlac City', parents_contact: '97723325805' },
  { id: 33, name: 'Rishelyne S. Balansag', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 16, birthday: '4/23/2010', address: 'Batang Batang Tarlac City', parents_contact: '9919857944' },
  { id: 34, name: 'Ceana Ghail R. Benson', chapter_area: 'EAST', role: 'Member', contact: '9658796230', email: '', status: 'Active', age: 17, birthday: '2/14/2009', address: 'Lapaz', parents_contact: '99109586974' },
  { id: 35, name: 'Matt Christian L. Pascua', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 16, birthday: '2/7/2010', address: 'Batang Batang Tarlac City', parents_contact: '9943765091' },
  { id: 36, name: 'John Carlo S. Daguro', chapter_area: 'EAST', role: 'Member', contact: '9942527797', email: '', status: 'Active', age: 16, birthday: '12/10/2009', address: 'Batang Batang Tarlac City', parents_contact: '' },
  { id: 37, name: 'Ella Tolentino', chapter_area: 'EAST', role: 'Member', contact: '9641514850', email: '', status: 'Active', age: 17, birthday: '5/23/2009', address: 'San Pascual, Tarlac City', parents_contact: '9101715799' },
  { id: 38, name: 'Rona Tacutaco', chapter_area: 'EAST', role: 'Member', contact: '9851636519', email: '', status: 'Active', age: 16, birthday: '8/9/2009', address: 'San Pascual, Tarlac City', parents_contact: '9569470391' },
  { id: 39, name: 'Aira Landingin', chapter_area: 'EAST', role: 'Member', contact: '9708718879', email: '', status: 'Active', age: 16, birthday: '7/7/2009', address: 'San Pascual, Tarlac City', parents_contact: '9758435309' },
  { id: 40, name: 'Ayesha B. Gadiana', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 9, birthday: '6/2/2016', address: 'San Isidro, Tarlac City', parents_contact: '9305555256' },
  { id: 41, name: 'Sean Ilagan', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '10/14/2011', address: 'Paniqui Tarlac', parents_contact: '9457716246' },
  { id: 42, name: 'Louis Ilagan', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 12, birthday: '12/26/2013', address: 'Paniqui Tarlac', parents_contact: '9457716246' },
  { id: 43, name: 'Andrean Jade Bravana', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 11, birthday: '8/1/2014', address: 'San Isidro, Tarlac City', parents_contact: '' },
  { id: 44, name: 'Prince John B. Gadiana', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 12, birthday: '3/26/2014', address: 'San Isidro, Tarlac City', parents_contact: '' },
  { id: 45, name: 'Kiann Sev B. Tejada', chapter_area: 'NORTH', role: 'Member', contact: '', email: '', status: 'Active', age: 15, birthday: '12/07/2010', address: 'Burgos, Paniqui Tarlac', parents_contact: '9560933949' },
  { id: 46, name: 'Lysander Uriel Ventura', chapter_area: 'NORTH', role: 'Member', contact: '', email: '', status: 'Active', age: 15, birthday: '1/22/2011', address: 'Paniqui Tarlac', parents_contact: '9395128453' },
  { id: 47, name: 'Raj Gabriel Pathak', chapter_area: 'NORTH', role: 'Member', contact: '', email: '', status: 'Active', age: 15, birthday: '3/25/2011', address: 'Pob. South Ramos', parents_contact: '9544973975' },
  { id: 48, name: 'Aljihin B. Caronongan', chapter_area: 'NORTH', role: 'Member', contact: '', email: '', status: 'Active', age: 15, birthday: '12/12/2010', address: 'Coral Paniqui Tarlac', parents_contact: '9276031736' },
  { id: 49, name: 'April Jane DelaCruz', chapter_area: 'WEST', role: 'Member', contact: '9926539259', email: '', status: 'Active', age: 15, birthday: '04/30/2011', address: 'Cabaruan, Purok 2 Sta. Ignacia, Tarlac', parents_contact: '9770490513' },
  { id: 50, name: 'Sharina Bona', chapter_area: 'WEST', role: 'Member', contact: '', email: '', status: 'Active', age: 15, birthday: '10/30/2010', address: 'San Francisco, Sta. Ignacia Tarlac', parents_contact: '9635901351' },
  { id: 51, name: 'Raphael Carl P. Rivera', chapter_area: 'WEST', role: 'Member', contact: '9562477438', email: '', status: 'Active', age: 15, birthday: '12/02/2010', address: 'Pob. West Sta. Ignacia Tarlac', parents_contact: '9275324598' },
  { id: 52, name: 'Jerecho P. Rivera', chapter_area: 'WEST', role: 'Member', contact: '9885851155', email: '', status: 'Active', age: 17, birthday: '10/19/2008', address: 'Pob. West Sta. Ignacia Tarlac', parents_contact: '9203408895' },
  { id: 53, name: 'Jay Aldrin A. Marticio', chapter_area: 'EAST', role: 'Member', contact: '9163282336', email: '', status: 'Active', age: 17, birthday: '04/29/2009', address: 'Pob. West Sta. Ignacia Tarlac', parents_contact: '9203408895' },
  { id: 54, name: 'Cyril John Roque', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '2/14/2012', address: 'Batang Batang Tarlac City', parents_contact: '9519893272' },
  { id: 55, name: 'Chena Mae Matias', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 17, birthday: '4/14/2010', address: 'Batang Batang Tarlac City', parents_contact: '9670072185' },
  { id: 56, name: 'Kian L. Notarlz', chapter_area: 'EAST', role: 'Member', contact: '9072536395', email: '', status: 'Active', age: 15, birthday: '12/9/2010', address: 'Batang Batang Tarlac City', parents_contact: '9457784480' },
  { id: 57, name: 'Fredierick R. Antalan', chapter_area: 'EAST', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '11/09/2011', address: 'Moncada, Tarlac', parents_contact: '' },
  { id: 58, name: 'Harrieth C. Valdez', chapter_area: 'NORTH', role: 'Member', contact: '9091990427', email: '', status: 'Active', age: 16, birthday: '9/24/2009', address: 'Moncada, Tarlac', parents_contact: '9272328857' },
  { id: 59, name: 'Evangeline M. Obilio', chapter_area: 'NORTH', role: 'Member', contact: '9648210825', email: '', status: 'Active', age: 14, birthday: '03/23/2012', address: 'Moncada, Tarlac', parents_contact: '9301028385' },
  { id: 60, name: 'Jona Mariz A. De Venecia', chapter_area: 'NORTH', role: 'Member', contact: '9058660828', email: '', status: 'Active', age: 15, birthday: '6/8/2010', address: 'Moncada, Tarlac', parents_contact: '9550847346' },
  { id: 61, name: 'Joevelyn Rhixzy G. Espejo', chapter_area: 'NORTH', role: 'Member', contact: '9639097664', email: '', status: 'Active', age: 18, birthday: '3/30/2008', address: 'Moncada, Tarlac', parents_contact: '9124661843' },
  { id: 62, name: 'Jhazelle E. Balmorez', chapter_area: 'NORTH', role: 'Member', contact: '9816860482', email: '', status: 'Active', age: 15, birthday: '10/20/2010', address: 'Moncada, Tarlac', parents_contact: '935309587' },
  { id: 63, name: 'Chedz Louise C. Tabilin', chapter_area: 'NORTH', role: 'Member', contact: '9816860482', email: '', status: 'Active', age: 13, birthday: '6/7/2012', address: 'Moncada, Tarlac', parents_contact: '9338156014' },
  { id: 64, name: 'Aron Kent G. Salvador', chapter_area: 'NORTH', role: 'Member', contact: '9615832773', email: '', status: 'Active', age: 18, birthday: '03/09/2008', address: 'Salumague, Paniqui Tarlac', parents_contact: '9300467865' },
  { id: 65, name: 'Fernando A. Dar', chapter_area: 'NORTH', role: 'Member', contact: '9454878873', email: '', status: 'Active', age: 18, birthday: '4/26/2008', address: 'Moncada, Tarlac', parents_contact: '9296699956' },
  { id: 66, name: 'Ma. Yvonne C. Niegos', chapter_area: 'NORTH', role: 'Member', contact: '9289720379', email: '', status: 'Active', age: 17, birthday: '9/9/2008', address: 'Moncada, Tarlac', parents_contact: '9957240313' },
  { id: 67, name: 'Leah Andrea C. Casica', chapter_area: 'NORTH', role: 'Member', contact: '9181583353', email: '', status: 'Active', age: 17, birthday: '4/5/2009', address: 'PacPaco San Manuel Moncada, Tarlac', parents_contact: '9488473102' },
  { id: 68, name: 'Renz Cyruz P. Sapla', chapter_area: 'NORTH', role: 'Member', contact: '9685853306', email: '', status: 'Active', age: 17, birthday: '10/14/2008', address: 'Moncada, Tarlac', parents_contact: '' },
  { id: 69, name: 'Sophia Reign C. Pujol', chapter_area: 'NORTH', role: 'Member', contact: '', email: '', status: 'Active', age: 12, birthday: '7/25/2013', address: 'Moncada, Tarlac', parents_contact: '' },
  { id: 70, name: 'Riley Tiffany B. Egipto', chapter_area: 'NORTH', role: 'Member', contact: '', email: '', status: 'Active', age: 16, birthday: '3/16/2010', address: 'Magaspac, Gerona Tarlac', parents_contact: '9278825052' },
  { id: 71, name: 'Antonia G. Egipto', chapter_area: 'NORTH', role: 'Member', contact: '', email: '', status: 'Active', age: 12, birthday: '6/28/2013', address: 'Magaspac, Gerona Tarlac', parents_contact: '9672539992' },
  { id: 72, name: 'Liselle Ondrea B. Egipto', chapter_area: 'NORTH', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '1/9/2012', address: 'Magaspac, Gerona Tarlac', parents_contact: '9278825052' },

  // 80 New Members (IDs 73-152)
  { id: 73, name: 'Agustin Fritzzy Ann Gabriel', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 74, name: 'Arnzenia Joy', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 75, name: 'Balagtas Jash F', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 76, name: 'Batiancila Crystal Francheska', chapter_area: '', role: 'Member', contact: '9510408904', email: 'skibidisigmaohio635@gmail.com', status: 'Active', age: 13, birthday: '04/03/2011', address: 'San Isidro Zone 1 Farmhouse', parents_contact: '' },
  { id: 77, name: 'Bautista Red', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 78, name: 'Bedruz Maria Cassandra', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 79, name: 'Bengco Arnie Nares', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 80, name: 'Bengco Reniel M.', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 81, name: 'Bernardo Leona Tolentino', chapter_area: '', role: 'Member', contact: '9635129447', email: 'Josabernardo0518@gmail.com', status: 'Active', age: 17, birthday: '05/18/2007', address: 'Blk. 3 San Manuel, Tarlac City', parents_contact: '' },
  { id: 82, name: 'Bernardo Rc', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 83, name: 'Bernardo Reycel', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 84, name: 'Briones Kyllie Yalung', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 12, birthday: '09/30/2011', address: 'Brgy. Salapungan', parents_contact: '' },
  { id: 85, name: 'Cabalu Mary Ann Villanueva', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 86, name: 'Calma Elle Sapphire Tria', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '09/18/2009', address: 'Salapungan, Tarlac City', parents_contact: '' },
  { id: 87, name: 'Calma Yael', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 13, birthday: '04/05/2011', address: 'Brgy. Salapungan', parents_contact: '' },
  { id: 88, name: 'Calugay Bryce', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 89, name: 'Canlas Pia', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 90, name: 'Cashero Cedrick', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 91, name: 'Chynna Angela', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 92, name: 'Condes Divine Samson', chapter_area: '', role: 'Member', contact: '9859319777', email: 'condesroylyn@gmail.com', status: 'Active', age: 17, birthday: '06/26/2007', address: 'Blk. 7, Brgy. San Jose, Tarlac City', parents_contact: '' },
  { id: 93, name: 'Corpuz Arzenia', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 94, name: 'Corpuz Raiza Mariano', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 95, name: 'Cruz Tricia', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 17, birthday: '05/17/2007', address: 'San Pascual, Tarlac City', parents_contact: '' },
  { id: 96, name: 'Cruz Tristan Jay', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 12, birthday: '05/08/2012', address: 'Brgy. San Pascual, Tarlac City', parents_contact: '' },
  { id: 97, name: 'Cunanan April', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 98, name: 'Dante', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 99, name: 'Dautil Neil Adrian Galvan', chapter_area: '', role: 'Member', contact: '9855566985', email: 'neiladriandautil@gmail.com', status: 'Active', age: 15, birthday: '08/20/2009', address: 'Sixto Hernandez Street, Block 1, San Manuel, Tarlac City', parents_contact: '' },
  { id: 100, name: 'De Leon Raymart', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 101, name: 'DeLeon Mika', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 102, name: 'Diesmo Mark', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 103, name: 'Dizon Jhenuary', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 104, name: 'Dizon Mj Quetua', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 16, birthday: '11/15/2007', address: 'Brgy. Salapungan', parents_contact: '' },
  { id: 105, name: 'Dizon Quetua', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 106, name: 'Doel Arriana Merc', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 107, name: 'Espiritu Haven', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 108, name: 'Espiritu Jasmin Anikka', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 109, name: 'Espiritu Jasmine', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 110, name: 'Espiritu Jelina', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 15, birthday: '03/30/2009', address: 'Brgy. BatangBatang, Tarlac City', parents_contact: '' },
  { id: 111, name: 'Evedientes Yuri Guinto', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 112, name: 'Facunla Sam', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 113, name: 'Felesario Marga', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 114, name: 'Gambito Kenlee', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 115, name: 'Jen Elle', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 116, name: 'Karmela Ina', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 117, name: 'Lacerna Chynna Angela', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 118, name: 'Lacsina Jaycee', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 119, name: 'Lhor Jhulius', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 120, name: 'Liwanag Mj', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 121, name: 'Luto Princess Reign Pangan', chapter_area: '', role: 'Member', contact: '9604104826', email: 'princessreignluto@gmail.com', status: 'Active', age: 13, birthday: '10/08/2011', address: 'San Pascual, Tarlac City', parents_contact: '' },
  { id: 122, name: 'Luto Reign', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 123, name: 'Ma Yvonne', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 124, name: 'Macapagal Ryza', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 125, name: 'MaÃ±alac Hazel', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 18, birthday: '10/21/2005', address: 'Brgy. Balibago II, Tarlac City', parents_contact: '' },
  { id: 126, name: 'Mandap Jhelaissa', chapter_area: '', role: 'Member', contact: '9079582030', email: 'jhlsxc@gmail.com', status: 'Active', age: 14, birthday: '03/12/2009', address: 'Blk. 2 San Manuel, Tarlac City', parents_contact: '' },
  { id: 127, name: 'Mandap Mica', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 17, birthday: '07/28/2007', address: 'Brgy. San Manuel, Tarlac City', parents_contact: '' },
  { id: 128, name: 'Masangcaty Sean Usher', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '10/24/2009', address: 'Tariji, Tarlac City', parents_contact: '' },
  { id: 129, name: 'Morales Elizabeth', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 16, birthday: '04/19/2008', address: 'Tariji, Tarlac City', parents_contact: '' },
  { id: 130, name: 'Obletas Christine Gampoy', chapter_area: '', role: 'Member', contact: '9851638293', email: 'obletaschristine@gmail.com', status: 'Active', age: 17, birthday: '10/08/2006', address: 'Tariji Zone 5, Tarlac City', parents_contact: '' },
  { id: 131, name: 'Palasigue Dante', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 132, name: 'Pamposa Angela Charlee', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 133, name: 'Razon Janelle P.', chapter_area: '', role: 'Member', contact: '9708288083', email: 'janellerazon966@gmail.com', status: 'Active', age: 19, birthday: '02/07/2005', address: 'Barangay Tariji Zone 6, Tarlac City', parents_contact: '' },
  { id: 134, name: 'Rivera Princess Fiona', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 135, name: 'Rivera Raylfarra', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 13, birthday: '09/22/2010', address: 'Brgy. Salapungan', parents_contact: '' },
  { id: 136, name: 'Salazar Tantan', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 137, name: 'Samson Jaezelle', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 138, name: 'Samson Jin Lacerna', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 139, name: 'Samson Juan Miguel L', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 13, birthday: '06/16/2011', address: 'Brgy. San Pascual, Tarlac City', parents_contact: '' },
  { id: 140, name: 'Sanluis Cara', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 17, birthday: '10/21/2006', address: 'Brgy. San Rafael, Tarlac City', parents_contact: '' },
  { id: 141, name: 'Sigua Daniel', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 142, name: 'Sosa Jzel', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 143, name: 'Suarez Humphrey Liriel', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 144, name: 'Tabilin Shaira', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 145, name: 'Tacusalme Yvonne', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 146, name: 'Tanedo Casimiro Miguel', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 12, birthday: '07/22/2012', address: 'San Isidro, Tarlac City', parents_contact: '' },
  { id: 147, name: 'Tolentino Chloe Tabios', chapter_area: '', role: 'Member', contact: '9318061977', email: 'chloetolentino7002@gmail.com', status: 'Active', age: 16, birthday: '09/13/2007', address: 'Blk 6, Brgy. San Manuel, Tarlac City', parents_contact: '' },
  { id: 148, name: 'Torres Lorrie Ramos', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 149, name: 'Valencia Alaicka', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 150, name: 'Villanueva Kayla', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' },
  { id: 151, name: 'Villegas Aleine Simon', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 14, birthday: '10/21/2009', address: 'Brgy. San Manuel, Tarlac City', parents_contact: '' },
  { id: 152, name: 'Yalung Nathaniel John Ballon', chapter_area: '', role: 'Member', contact: '', email: '', status: 'Active', age: 0, birthday: '', address: '', parents_contact: '' }
];

const SAMPLE_ACTIVITIES = [
  { id: 1, month: 'January', week: '1st Week', date: '2026-01-04', activity: 'Upper Core Household', chapter_area: 'AREA', status: 'Accomplished', held_in: 'Face to Face', participants: 3, venue: '', coordinator_id: 1, attendee_ids: [1, 3, 6] },
  { id: 2, month: 'January', week: '2nd Week', date: '2026-01-10', activity: 'LCSC Summit', chapter_area: '', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 3, month: 'January', week: '2nd Week', date: '2026-01-10', activity: 'Chapter Household', chapter_area: 'EAST', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 4, month: 'January', week: '2nd Week', date: '2026-01-10', activity: 'Chapter Household', chapter_area: 'WEST', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 5, month: 'January', week: '2nd Week', date: '2026-01-10', activity: 'Chapter Household', chapter_area: 'NORTH', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 6, month: 'January', week: '2nd Week', date: '2026-01-10', activity: 'Chapter Household', chapter_area: 'SOUTH', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 7, month: 'January', week: '', date: '2026-01-18', activity: 'Community Conference', chapter_area: '', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 8, month: 'January', week: '3rd Week', date: '2026-01-17', activity: 'Upper Core Household / MTD', chapter_area: 'AREA', status: 'Accomplished', held_in: 'Online', participants: 2, venue: '', coordinator_id: 3, attendee_ids: [3, 6] },
  { id: 9, month: 'January', week: '4th Week', date: '2026-01-24', activity: 'Area Assembly', chapter_area: 'AREA', status: 'Accomplished', held_in: 'Face to Face', participants: 7, venue: 'Saint Raymond Nonnatus, Moncada', coordinator_id: 3, attendee_ids: [1, 2, 3, 4, 6, 7, 8] },
  { id: 10, month: 'January', week: '4th Week', date: '2026-01-25', activity: 'LIT Year Starter', chapter_area: 'LIT', status: 'Accomplished', held_in: 'Face to Face', participants: 1, venue: '', coordinator_id: 7, attendee_ids: [7] },
  { id: 11, month: 'January', week: '5th Week', date: '2026-01-31', activity: 'LCSC Forum', chapter_area: 'AREA', status: 'Accomplished', held_in: '', participants: 0, venue: 'Our Lady of Ransom', coordinator_id: null, attendee_ids: [] },
  { id: 12, month: 'January', week: '5th Week', date: '2026-01-31', activity: 'HeartChamp Training', chapter_area: '', status: '', held_in: '', participants: 0, venue: 'Patalan Farm - Paniqui', coordinator_id: null, attendee_ids: [] },
  { id: 13, month: 'February', week: '1st Week', date: '2026-02-01', activity: 'Servant Leaders Summit', chapter_area: 'UPPER CORE', status: 'Accomplished', held_in: 'Face to Face', participants: 6, venue: '', coordinator_id: 6, attendee_ids: [1, 2, 3, 4, 6, 8] },
  { id: 14, month: 'February', week: '2nd Week', date: '2026-02-07', activity: 'Couple Coordinators Training', chapter_area: 'TRAINING', status: 'Accomplished', held_in: 'Face to Face', participants: 4, venue: '', coordinator_id: 8, attendee_ids: [1, 2, 6, 8] },
  { id: 15, month: 'February', week: '2nd Week', date: '2026-02-08', activity: 'Chapter Household', chapter_area: 'SOUTH', status: 'Cancelled', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 16, month: 'February', week: '2nd Week', date: '2026-02-08', activity: 'Chapter Household', chapter_area: 'EAST', status: 'Cancelled', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 17, month: 'February', week: '2nd Week', date: '2026-02-08', activity: 'Chapter Household', chapter_area: 'WEST', status: 'Cancelled', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 18, month: 'February', week: '2nd Week', date: '2026-02-08', activity: 'Chapter Household', chapter_area: 'NORTH', status: 'Rescheduled', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 19, month: 'February', week: '', date: '2026-02-15', activity: 'World Couples Congress', chapter_area: '', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 20, month: 'February', week: '', date: '2026-02-17', activity: 'Chapter Household', chapter_area: 'NORTH', status: 'Accomplished', held_in: 'Face to Face', participants: 2, venue: '', coordinator_id: 4, attendee_ids: [4, 1] },
  { id: 21, month: 'February', week: '3rd Week', date: '2026-02-21', activity: 'LivePure Forum', chapter_area: 'AREA', status: 'Accomplished', held_in: 'Face to Face', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 22, month: 'February', week: '3rd Week', date: '2026-02-21', activity: 'Upper Core Household', chapter_area: 'AREA', status: 'Accomplished', held_in: 'Face to Face', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 23, month: 'February', week: '3rd Week', date: '2026-02-22', activity: 'Household Servants Training', chapter_area: 'TRAINING', status: 'Accomplished', held_in: 'Face to Face', participants: 2, venue: '', coordinator_id: 8, attendee_ids: [8, 7] },
  { id: 24, month: 'February', week: '4th Week', date: '2026-02-28', activity: 'Chapter Assembly', chapter_area: 'SOUTH', status: 'Cancelled', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 25, month: 'February', week: '4th Week', date: '2026-02-28', activity: 'Chapter Assembly', chapter_area: 'EAST', status: 'Accomplished', held_in: 'Online', participants: 3, venue: '', coordinator_id: 1, attendee_ids: [1, 2, 5] },
  { id: 26, month: 'February', week: '4th Week', date: '2026-02-28', activity: 'Chapter Assembly', chapter_area: 'WEST', status: 'Accomplished', held_in: 'Face to Face', participants: 2, venue: '', coordinator_id: 2, attendee_ids: [2, 3] },
  { id: 27, month: 'February', week: '4th Week', date: '2026-02-28', activity: 'Chapter Assembly', chapter_area: 'NORTH', status: 'Accomplished', held_in: 'Online', participants: 2, venue: '', coordinator_id: 4, attendee_ids: [4, 6] },
  { id: 28, month: 'March', week: '1st Week', date: '2026-03-01', activity: 'Go Beyond Mission Training', chapter_area: 'UPPER CORE', status: 'Accomplished', held_in: 'Face to Face', participants: 5, venue: '', coordinator_id: 6, attendee_ids: [1, 3, 4, 6, 8] },
  { id: 29, month: 'March', week: '1st Week', date: '2026-03-08', activity: 'Upper Core Household/MTD', chapter_area: 'AREA', status: 'Accomplished', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 30, month: 'March', week: '2nd Week', date: '2026-03-14', activity: 'Chapter Household', chapter_area: 'SOUTH', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 31, month: 'March', week: '2nd Week', date: '2026-03-14', activity: 'Chapter Household', chapter_area: 'EAST', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 32, month: 'March', week: '2nd Week', date: '2026-03-14', activity: 'Chapter Household', chapter_area: 'WEST', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 33, month: 'March', week: '2nd Week', date: '2026-03-14', activity: 'Chapter Household', chapter_area: 'NORTH', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] },
  { id: 34, month: 'March', week: '3rd Week', date: '2026-03-21', activity: 'Walk for Life, Walk for Unity', chapter_area: 'AREA', status: '', held_in: '', participants: 0, venue: '', coordinator_id: null, attendee_ids: [] }
];
